import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#b52330",
        "primary-container": "#ff5a5f",
        "on-primary": "#ffffff",
        "on-primary-container": "#61000e",
        "secondary": "#685d4a",
        "secondary-container": "#eddec5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6c614e",
        "tertiary": "#006e25",
        "tertiary-container": "#2ba947",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#00350d",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fff8f7",
        "on-background": "#261817",
        "surface": "#fff8f7",
        "on-surface": "#261817",
        "surface-variant": "#f7dcdb",
        "on-surface-variant": "#5a403f",
        "outline": "#8e706f",
        "outline-variant": "#e2bebc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff0ef",
        "surface-container": "#ffe9e7",
        "surface-container-high": "#fde2e0",
        "surface-container-highest": "#f7dcdb",
        "surface-bright": "#fff8f7",
        "surface-dim": "#efd4d2",
        "inverse-surface": "#3d2c2c",
        "inverse-on-surface": "#ffedeb",
        "inverse-primary": "#ffb3b0",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b0",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#92001b",
        "secondary-fixed": "#f0e0c8",
        "secondary-fixed-dim": "#d3c5ad",
        "on-secondary-fixed": "#221b0b",
        "on-secondary-fixed-variant": "#4f4533",
        "tertiary-fixed": "#83fc8e",
        "tertiary-fixed-dim": "#66df75",
        "on-tertiary-fixed": "#002106",
        "on-tertiary-fixed-variant": "#00531a",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
