services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: hungnguyen
      POSTGRES_PASSWORD: hung2004
      POSTGRES_DB: HanoiGO_db
    ports: ["5433:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  adminer:
    image: adminer
    ports: ["8080:8080"]

volumes:
  postgres_data:
